project:
  type: website
lang: es
text-align: justify


website:
  title: "CIENCIA SIMPLE"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/soffpin/FLORES
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

