---
title: "Aprendiendo a cultivar"
author: "Ana Sofía Pineda"
date: "2024-06-28"
categories: [Artículos]
lang: es
text-align: justify
font-family: arial
font-size: 15%
color: black
---

Hola! Este es mi primer post.

Me llamo Ana Sofía Pineda, soy ingeniera agrónoma y estoy actualmente estoy estudiando la Maestría en Ciencias Agropecuarias en la Facultad de Ciencias Agrícolas *Campus Xalapa* perteneciente a la Universidad Veracruzana. Me encantan las plantas, la naturaleza y el trabajo de campo. A lo largo de mi carrera, probé el trabajo en distintas ramas de la agronomía pero ninguna me convenció, hasta que encontré la agricultura protegida (AP), donde aprendí a cultivar hortalizas en condiciones protegidas, tanto en invernadero, como en campo abierto, además del manejo de sistemas hidropónicos.

Elegir la agricultura protegida como mi área de interés no sólo me trajo conocimientos técnicos, también aprendí mucho sobre el trabajo en equipo, la cooperación y el compañerismo, pero sin duda, uno de los mejores descubrimientos que me trajo esta decisión, fue mi gusto por la investigación científica.

Desarrollé un sistema hidropónico de raíz flotante para especies de hoja. Lo novedoso de este proyecto es que, en la fase de germinación de mis plantitas, las nutrí con microorganismos benéficos (*Bacillus subtillis, Trichoderma harzianum* y *Azospirillum brasilense*)

pensar que el propósito de generar conocimiento es compartirlo de una forma en la que todos podamos aprender sobre los nuevos descubrimientos de la ciencia sin importar nuestra ocupación.
