---
title: "Aprendiendo a cultivar"
author: "Ana Sofía Pineda"
date: "2024-06-30"
categories: [Artículos]
lang: es
text-align: justify
---

::: {style="font-family: arial;font-size: 20px;color: black;text-align: justify"}
Hola!

Me llamo Ana Sofía Pineda, soy ingeniera agrónoma y actualmente estoy estudiando la Maestría en Ciencias Agropecuarias en la Facultad de Ciencias Agrícolas *Campus Xalapa* perteneciente a la Universidad Veracruzana. Me encantan las plantas, la naturaleza y el trabajo de campo. Me gusta pensar que el propósito de generar conocimiento es compartirlo de una forma en la que todos podamos aprender sobre los nuevos descubrimientos de la ciencia sin importar nuestra ocupación. Yo creo que nunca es tarde para aprender o dedicarse a cosas nuevas, ya que así fue como descubrí mi gusto por la investigación, la escritura y la divulgación del conocimiento. Es por ello que he creado este blog, con el fin de compartir de manera sencilla los descubrimientos que estoy generando. 
:::

::: {style="font-family: arial;font-size: 25px;color: black;text-align: center"}
BIENVENIDOS! :)
:::
